CREATE TABLE IF NOT EXISTS warehouse_product_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL REFERENCES warehouses(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    min_stock_quantity NUMERIC(18, 3) NOT NULL,
    CONSTRAINT uq_warehouse_product_settings_warehouse_product UNIQUE (warehouse_id, product_id),
    CONSTRAINT ck_warehouse_product_settings_minimum CHECK (min_stock_quantity >= 0)
);

CREATE INDEX IF NOT EXISTS idx_warehouse_product_settings_product
    ON warehouse_product_settings (product_id);
