CREATE TABLE IF NOT EXISTS inventory_alert_incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_key VARCHAR(120) NOT NULL,
    kind VARCHAR(30) NOT NULL,
    severity VARCHAR(30) NOT NULL,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    warehouse_id BIGINT NOT NULL REFERENCES warehouses(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    lot_id BIGINT REFERENCES product_lots(id),
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT ck_inventory_alert_kind CHECK (kind IN ('low_stock', 'expiry')),
    CONSTRAINT ck_inventory_alert_severity CHECK (severity IN ('low_stock', 'expiring', 'expired')),
    CONSTRAINT ck_inventory_alert_status CHECK ((status = 'open' AND resolved_at IS NULL) OR (status = 'resolved' AND resolved_at IS NOT NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_alert_open_key
    ON inventory_alert_incidents (incident_key) WHERE status = 'open';

CREATE INDEX IF NOT EXISTS ix_inventory_alert_branch_status
    ON inventory_alert_incidents (branch_id, status, opened_at DESC);
