<?php

use App\Http\Controllers\CatalogController;
use App\Http\Controllers\CatalogWriteController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DebtController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\InventoryAlertController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\OutboxController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProductContentController;
use App\Http\Controllers\PurchaseReceiptController;
use App\Http\Controllers\SalesOrderController;
use App\Http\Controllers\SalesReportController;
use App\Http\Controllers\StockTransferController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\UserManagementController;
use App\Http\Middleware\EnsureActiveUser;
use App\Http\Middleware\SerializeBigIntIds;
use App\Http\Middleware\ValidateBigIntRouteIds;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth:sanctum', EnsureActiveUser::class, ValidateBigIntRouteIds::class, SerializeBigIntIds::class])->group(function (): void {
    Route::get('/me', [ProfileController::class, 'show']);
    Route::get('/outbox', [OutboxController::class, 'index']);
    Route::post('/outbox/{id}/retry', [OutboxController::class, 'retry'])->whereNumber('id');
    Route::get('/users', [UserManagementController::class, 'index']);
    Route::post('/users', [UserManagementController::class, 'store']);
    Route::patch('/users/{id}/active', [UserManagementController::class, 'setActive'])->whereNumber('id');
    Route::post('/users/{id}/assignments', [UserManagementController::class, 'grant'])->whereNumber('id');
    Route::post('/assignments/{id}/revoke', [UserManagementController::class, 'revoke'])->whereNumber('id');
    Route::get('/inventory', [InventoryController::class, 'index']);
    Route::get('/debts', [DebtController::class, 'index']);
    Route::post('/debts/{id}/payments', [DebtController::class, 'pay'])->whereNumber('id');
    Route::get('/inventory/movements', [InventoryController::class, 'movements']);
    Route::get('/inventory/alerts', [InventoryAlertController::class, 'index']);
    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::patch('/notifications/{id}/read', [NotificationController::class, 'markRead']);
    Route::get('/inventory/thresholds', [InventoryAlertController::class, 'thresholds']);
    Route::put('/inventory/thresholds/{warehouseId}/{productId}', [InventoryAlertController::class, 'setThreshold'])->whereNumber(['warehouseId', 'productId']);
    Route::get('/stock-transfers', [StockTransferController::class, 'index']);
    Route::get('/stock-transfers/options', [StockTransferController::class, 'options']);
    Route::get('/stock-transfers/{id}', [StockTransferController::class, 'show'])->whereNumber('id');
    Route::post('/stock-transfers', [StockTransferController::class, 'store']);
    Route::post('/stock-transfers/{id}/approve', [StockTransferController::class, 'approve'])->whereNumber('id');
    Route::post('/stock-transfers/{id}/reject', [StockTransferController::class, 'reject'])->whereNumber('id');
    Route::post('/stock-transfers/{id}/dispatch', [StockTransferController::class, 'dispatch'])->whereNumber('id');
    Route::post('/stock-transfers/{id}/receive', [StockTransferController::class, 'receive'])->whereNumber('id');
    Route::post('/stock-transfers/{id}/reconcile', [StockTransferController::class, 'reconcile'])->whereNumber('id');
    Route::get('/catalog', [CatalogController::class, 'index']);
    Route::get('/catalog/products/{id}/content', [ProductContentController::class, 'show'])->whereNumber('id');
    Route::put('/catalog/products/{id}/content', [ProductContentController::class, 'update'])->whereNumber('id');
    Route::get('/organization', [OrganizationController::class, 'index']);
    Route::post('/organization/chains', [OrganizationController::class, 'createChain']);
    Route::patch('/organization/chains/{id}', [OrganizationController::class, 'updateChain'])->whereNumber('id');
    Route::post('/organization/branches', [OrganizationController::class, 'createBranch']);
    Route::patch('/organization/branches/{id}', [OrganizationController::class, 'updateBranch'])->whereNumber('id');
    Route::post('/organization/warehouses', [OrganizationController::class, 'createWarehouse']);
    Route::patch('/organization/warehouses/{id}', [OrganizationController::class, 'updateWarehouse'])->whereNumber('id');
    Route::get('/suppliers', [SupplierController::class, 'index']);
    Route::get('/customers', [CustomerController::class, 'index']);
    Route::post('/customers', [CustomerController::class, 'store']);
    Route::patch('/customers/{id}', [CustomerController::class, 'update'])->whereNumber('id');
    Route::post('/suppliers', [SupplierController::class, 'store']);
    Route::patch('/suppliers/{id}', [SupplierController::class, 'update'])->whereNumber('id');
    Route::get('/purchase-receipts', [PurchaseReceiptController::class, 'index']);
    Route::get('/sales-orders', [SalesOrderController::class, 'index']);
    Route::get('/reports/sales', [SalesReportController::class, 'index']);
    Route::get('/sales-orders/options', [SalesOrderController::class, 'options']);
    Route::get('/sales-orders/{id}', [SalesOrderController::class, 'show'])->whereNumber('id');
    Route::post('/sales-orders', [SalesOrderController::class, 'store']);
    Route::post('/sales-orders/{id}/confirm', [SalesOrderController::class, 'confirm'])->whereNumber('id');
    Route::get('/purchase-receipts/options', [PurchaseReceiptController::class, 'options']);
    Route::get('/purchase-receipts/{id}', [PurchaseReceiptController::class, 'show'])->whereNumber('id');
    Route::post('/purchase-receipts', [PurchaseReceiptController::class, 'store']);
    Route::put('/purchase-receipts/{id}', [PurchaseReceiptController::class, 'update'])->whereNumber('id');
    Route::post('/purchase-receipts/{id}/submit', [PurchaseReceiptController::class, 'submit'])->whereNumber('id');
    Route::post('/purchase-receipts/{id}/approve', [PurchaseReceiptController::class, 'approve'])->whereNumber('id');
    Route::post('/purchase-receipts/{id}/reject', [PurchaseReceiptController::class, 'reject'])->whereNumber('id');
    Route::post('/catalog/categories', [CatalogWriteController::class, 'createCategory']);
    Route::patch('/catalog/categories/{id}', [CatalogWriteController::class, 'updateCategory'])->whereNumber('id');
    Route::post('/catalog/units', [CatalogWriteController::class, 'createUnit']);
    Route::patch('/catalog/units/{id}', [CatalogWriteController::class, 'updateUnit'])->whereNumber('id');
    Route::post('/catalog/products', [CatalogWriteController::class, 'createProduct']);
    Route::patch('/catalog/products/{id}', [CatalogWriteController::class, 'updateProduct'])->whereNumber('id');
});
