BEGIN;

CREATE TABLE chains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id BIGINT NOT NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(160) NOT NULL,
    address TEXT,
    default_sales_warehouse_id BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_branches_chain_code UNIQUE (chain_id, code),
    CONSTRAINT fk_branches_chain FOREIGN KEY (chain_id) REFERENCES chains(id),
    CONSTRAINT ck_branches_active_default_warehouse CHECK (NOT is_active OR default_sales_warehouse_id IS NOT NULL)
);

CREATE TABLE warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(160) NOT NULL,
    warehouse_type VARCHAR(40) NOT NULL,
    CONSTRAINT uq_warehouses_branch_code UNIQUE (branch_id, code),
    CONSTRAINT uq_warehouses_branch_id UNIQUE (branch_id, id),
    CONSTRAINT fk_warehouses_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
);

ALTER TABLE branches
    ADD CONSTRAINT fk_branches_default_sales_warehouse
    FOREIGN KEY (id, default_sales_warehouse_id)
    REFERENCES warehouses(branch_id, id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_catalog_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_users_one_catalog_admin ON users ((is_catalog_admin)) WHERE is_catalog_admin;

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL
);

CREATE TABLE user_role_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    branch_id BIGINT,
    starts_on DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    CONSTRAINT fk_user_role_assignments_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_role_assignments_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_user_role_assignments_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    customer_type VARCHAR(30) NOT NULL,
    phone VARCHAR(30),
    address TEXT,
    CONSTRAINT fk_customers_chain FOREIGN KEY (chain_id) REFERENCES chains(id)
);

CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    phone VARCHAR(30),
    address TEXT,
    CONSTRAINT fk_suppliers_chain FOREIGN KEY (chain_id) REFERENCES chains(id)
);

CREATE TABLE product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_product_categories_parent FOREIGN KEY (parent_id) REFERENCES product_categories(id),
    CONSTRAINT ck_product_categories_not_self CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE TABLE units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    code VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    active_ingredient VARCHAR(200),
    sale_price NUMERIC(18, 2) NOT NULL DEFAULT 0,
    tax_rate NUMERIC(5, 2),
    expiry_warning_days INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES product_categories(id),
    CONSTRAINT fk_products_unit FOREIGN KEY (unit_id) REFERENCES units(id),
    CONSTRAINT ck_products_sale_price CHECK (sale_price >= 0),
    CONSTRAINT ck_products_tax_rate CHECK (tax_rate IS NULL OR (tax_rate >= 0 AND tax_rate <= 100)),
    CONSTRAINT ck_products_expiry_warning_days CHECK (expiry_warning_days IS NULL OR (expiry_warning_days >= 0 AND expiry_warning_days <= 3650))
);

CREATE TABLE product_lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    lot_no VARCHAR(80) NOT NULL,
    manufactured_on DATE,
    expires_on DATE,
    CONSTRAINT uq_product_lots_product_no UNIQUE (product_id, lot_no),
    CONSTRAINT fk_product_lots_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT ck_product_lots_dates CHECK (manufactured_on IS NULL OR expires_on IS NULL OR expires_on > manufactured_on)
);

CREATE TABLE inventories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL,
    lot_id BIGINT NOT NULL,
    quantity NUMERIC(18, 3) NOT NULL DEFAULT 0,
    average_unit_cost NUMERIC(18, 6),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_inventories_warehouse_lot UNIQUE (warehouse_id, lot_id),
    CONSTRAINT fk_inventories_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_inventories_lot FOREIGN KEY (lot_id) REFERENCES product_lots(id),
    CONSTRAINT ck_inventories_quantity CHECK (quantity >= 0),
    CONSTRAINT ck_inventories_average_cost CHECK (average_unit_cost IS NULL OR average_unit_cost >= 0)
);

CREATE TABLE purchase_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    approved_by BIGINT,
    rejected_by BIGINT,
    receipt_no VARCHAR(60) NOT NULL UNIQUE,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at TIMESTAMPTZ,
    approved_at TIMESTAMPTZ,
    rejected_at TIMESTAMPTZ,
    rejection_reason TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_purchase_receipts_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_purchase_receipts_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_purchase_receipts_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_purchase_receipts_approver FOREIGN KEY (approved_by) REFERENCES users(id),
    CONSTRAINT fk_purchase_receipts_rejecter FOREIGN KEY (rejected_by) REFERENCES users(id),
    CONSTRAINT ck_purchase_receipts_total CHECK (total_amount >= 0),
    CONSTRAINT ck_purchase_receipts_status CHECK (status IN ('draft', 'submitted', 'approved', 'rejected')),
    CONSTRAINT ck_purchase_receipts_different_approver CHECK ((approved_by IS NULL OR approved_by <> created_by) AND (rejected_by IS NULL OR rejected_by <> created_by))
);

CREATE TABLE purchase_receipt_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id BIGINT NOT NULL,
    lot_id BIGINT NOT NULL,
    quantity NUMERIC(18, 3) NOT NULL,
    unit_cost NUMERIC(18, 2) NOT NULL,
    line_total NUMERIC(18, 2) NOT NULL,
    CONSTRAINT uq_purchase_receipt_items_receipt_lot UNIQUE (receipt_id, lot_id),
    CONSTRAINT fk_purchase_receipt_items_receipt FOREIGN KEY (receipt_id) REFERENCES purchase_receipts(id),
    CONSTRAINT fk_purchase_receipt_items_lot FOREIGN KEY (lot_id) REFERENCES product_lots(id),
    CONSTRAINT ck_purchase_receipt_items_amounts CHECK (quantity > 0 AND unit_cost >= 0 AND line_total >= 0)
);

CREATE TABLE sales_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL,
    customer_id BIGINT,
    created_by BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    order_no VARCHAR(60) NOT NULL UNIQUE,
    sold_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_sales_orders_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT fk_sales_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_sales_orders_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_sales_orders_export_warehouse FOREIGN KEY (branch_id, warehouse_id) REFERENCES warehouses(branch_id, id),
    CONSTRAINT ck_sales_orders_total CHECK (total_amount >= 0)
);

CREATE TABLE sales_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    lot_id BIGINT NOT NULL,
    quantity NUMERIC(18, 3) NOT NULL,
    unit_price NUMERIC(18, 2) NOT NULL,
    discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    line_total NUMERIC(18, 2) NOT NULL,
    unit_cost_snapshot NUMERIC(18, 6),
    cost_total NUMERIC(18, 2),
    tax_rate_snapshot NUMERIC(5, 2),
    tax_amount NUMERIC(18, 2),
    CONSTRAINT uq_sales_order_items_order_lot UNIQUE (order_id, lot_id),
    CONSTRAINT fk_sales_order_items_order FOREIGN KEY (order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_sales_order_items_lot FOREIGN KEY (lot_id) REFERENCES product_lots(id),
    CONSTRAINT ck_sales_order_items_amounts CHECK (quantity > 0 AND unit_price >= 0 AND discount_amount >= 0 AND line_total >= 0),
    CONSTRAINT ck_sales_order_items_cost_snapshot CHECK ((unit_cost_snapshot IS NULL AND cost_total IS NULL) OR (unit_cost_snapshot >= 0 AND cost_total >= 0)),
    CONSTRAINT ck_sales_order_items_tax_snapshot CHECK ((tax_rate_snapshot IS NULL AND tax_amount IS NULL) OR (tax_rate_snapshot >= 0 AND tax_rate_snapshot <= 100 AND tax_amount >= 0))
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id BIGINT NOT NULL UNIQUE,
    invoice_no VARCHAR(60) NOT NULL UNIQUE,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subtotal NUMERIC(18, 2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    CONSTRAINT fk_invoices_sales_order FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id),
    CONSTRAINT ck_invoices_amounts CHECK (subtotal >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    method VARCHAR(40) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    CONSTRAINT ck_payments_amount CHECK (amount > 0)
);

CREATE TABLE stock_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_warehouse_id BIGINT NOT NULL,
    to_warehouse_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    approved_by BIGINT,
    transfer_no VARCHAR(60) NOT NULL UNIQUE,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL DEFAULT 'requested',
    CONSTRAINT fk_stock_transfers_source_warehouse FOREIGN KEY (from_warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_stock_transfers_target_warehouse FOREIGN KEY (to_warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_stock_transfers_requester FOREIGN KEY (requested_by) REFERENCES users(id),
    CONSTRAINT fk_stock_transfers_approver FOREIGN KEY (approved_by) REFERENCES users(id),
    CONSTRAINT ck_stock_transfers_distinct_warehouses CHECK (from_warehouse_id <> to_warehouse_id)
);

CREATE TABLE stock_transfer_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id BIGINT NOT NULL,
    lot_id BIGINT NOT NULL,
    requested_quantity NUMERIC(18, 3) NOT NULL,
    dispatched_quantity NUMERIC(18, 3) NOT NULL DEFAULT 0,
    received_quantity NUMERIC(18, 3) NOT NULL DEFAULT 0,
    CONSTRAINT uq_stock_transfer_items_transfer_lot UNIQUE (transfer_id, lot_id),
    CONSTRAINT fk_stock_transfer_items_transfer FOREIGN KEY (transfer_id) REFERENCES stock_transfers(id),
    CONSTRAINT fk_stock_transfer_items_lot FOREIGN KEY (lot_id) REFERENCES product_lots(id),
    CONSTRAINT ck_stock_transfer_items_quantities CHECK (requested_quantity > 0 AND dispatched_quantity >= 0 AND received_quantity >= 0)
);

CREATE TABLE debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    supplier_id BIGINT,
    debt_type VARCHAR(10) NOT NULL,
    opening_balance NUMERIC(18, 2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    CONSTRAINT fk_debts_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_debts_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    CONSTRAINT ck_debts_exactly_one_partner CHECK (num_nonnulls(customer_id, supplier_id) = 1),
    CONSTRAINT ck_debts_partner_type CHECK ((debt_type = 'receivable' AND customer_id IS NOT NULL) OR (debt_type = 'payable' AND supplier_id IS NOT NULL)),
    CONSTRAINT ck_debts_opening_balance CHECK (opening_balance >= 0)
);

CREATE TABLE debt_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id BIGINT NOT NULL,
    payment_id BIGINT,
    transaction_type VARCHAR(30) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_debt_transactions_debt FOREIGN KEY (debt_id) REFERENCES debts(id),
    CONSTRAINT fk_debt_transactions_payment FOREIGN KEY (payment_id) REFERENCES payments(id),
    CONSTRAINT ck_debt_transactions_amount CHECK (amount > 0)
);

CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL,
    lot_id BIGINT NOT NULL,
    purchase_receipt_id BIGINT,
    sales_order_id BIGINT,
    stock_transfer_id BIGINT,
    movement_type VARCHAR(30) NOT NULL,
    quantity_delta NUMERIC(18, 3) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_movements_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT fk_stock_movements_lot FOREIGN KEY (lot_id) REFERENCES product_lots(id),
    CONSTRAINT fk_stock_movements_purchase_receipt FOREIGN KEY (purchase_receipt_id) REFERENCES purchase_receipts(id),
    CONSTRAINT fk_stock_movements_sales_order FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id),
    CONSTRAINT fk_stock_movements_stock_transfer FOREIGN KEY (stock_transfer_id) REFERENCES stock_transfers(id),
    CONSTRAINT ck_stock_movements_exactly_one_source CHECK (num_nonnulls(purchase_receipt_id, sales_order_id, stock_transfer_id) = 1),
    CONSTRAINT ck_stock_movements_quantity_delta CHECK (quantity_delta <> 0)
);

CREATE UNIQUE INDEX uq_stock_movements_purchase_lot ON stock_movements (purchase_receipt_id, warehouse_id, lot_id) WHERE purchase_receipt_id IS NOT NULL;
CREATE UNIQUE INDEX uq_stock_movements_sale_lot ON stock_movements (sales_order_id, warehouse_id, lot_id) WHERE sales_order_id IS NOT NULL;

CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ
);

COMMIT;
